# Generated by Django 4.2.1 on 2023-05-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_avaliacao_options_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliacao',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
